apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: passkey
  labels:
    auth.halo.run/auth-binding: "false"
spec:
  displayName: 通行密钥
  description: 使用通行密钥 (Passkey/WebAuthn) 进行无密码认证，支持指纹、面容或设备 PIN 码
  logo: /plugins/auth-passkey/assets/static/passkey.svg
  website: https://passkeys.io
  authenticationUrl: /apis/api.passkey.halo.run/v1alpha1/authentication/verify
  method: POST
  authType: form
  rememberMeSupport: true
